### PR TITLE
TZ and doc fixes

### PR DESCRIPTION
**Pull request by pwolanin**

### CODE REVIEW

**Comment by davidstrauss** [comment]
These changes look great, but can you resolve the conflict? It looks like we've both been busy. :-)

I can also resolve it if you would prefer, but then I'll get the commit attribution.

**Comment by pwolanin** [comment]
ok, will rebase and resolve

**Comment by pwolanin** [comment]
@mbaynton  it seems like it's rendering for me and on github without them

**Comment by mbaynton** [comment]
Hmm I dunno. The original commit lacked them and there were no line breaks. Obviously whatever works is fine.

**Comment by davidstrauss** [comment]
I don't think the trailing spaces are necessary for rendering, so I merged this. We can add them back if we notice issues.

**Pull request merged**
